#!/usr/bin/env python3
import os
import sys
import re

MY_DIR = os.path.dirname(os.path.realpath(__file__))

if os.path.isfile(os.path.join(MY_DIR, "marlininfo", "__init__.py")):
    sys.path.insert(0, MY_DIR)

from marlininfo import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
