#!/usr/bin/env python3
import sys
import re

from find_marlininfo import marlininfo
# ^ works for submodules too since changes sys.path

from marlininfo.filacalc import (
    main,
)

if __name__ == "__main__":
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
